pipeline {
    agent none
    stages {
        stage('Checkout') {
            agent any
            steps {                
                checkout([$class: 'GitSCM', 
				branches: [[name: "origin/master"]], 
				userRemoteConfigs: [[
                url: 'https://github.com/pipelineascodecourse/pipeline-agent-dockerfile.git']],
				extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'checkout-directory']]
				])
  // this extensions tells to Jenkins to checkout code within 'checkout-directory' in default workspace directory
            }
        }
        stage('dockerfile'){            
            agent {
                dockerfile {
                    customWorkspace '/var/lib/jenkins/workspace/pipeline-agent-dockerfile-customWorkspace/checkout-directory'
                } 
            }            
            steps{
                sh 'cat /etc/lsb-release'
            }
        }
    }
}

