pipeline {
    agent none
    stages {
        stage('Checkout') {
            agent any
            steps {
                checkout([$class: 'GitSCM', 
				branches: [[name: "origin/master"]], 
				userRemoteConfigs: [[
                url: 'https://github.com/pipelineascodecourse/pipeline-agent-dockerfile-dir.git']],
				])
            }
        }        
        stage('dockerfile'){
            agent { 
                dockerfile {                    
					dir 'dockerfileDir'
                } 
            }
            steps{
                sh 'cat /etc/lsb-release'
            }
        }
    }
}


______________________

pipeline {
    agent none
    stages {
        stage('Checkout') {
            agent {
                node {
                    label 'docker'
                }
            }
            steps {
                
                checkout([$class: 'GitSCM', 
				branches: [[name: "origin/master"]], 
				userRemoteConfigs: [[
                url: 'https://github.com/dandu1008/pipeline-agent-dockerfile-filename.git']]
				])
            }
        }
        stage('dockerfile'){            
            agent {
                    dockerfile {
                        dir 'docker'
                        filename 'mycustomdocker'
                    }
            }
            steps{
                sh 'cat /etc/lsb-release'			
            }
        }
    }
}

